### ISSUE TITLE
在运行了一段时间后会出现如下错误提示，然后会有超高CPU占用

### ISSUE THREAD

**Issue by Galel** [twocucao/danmu.fm#11]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/danmufm/client/douyu_danmu_manager.py", line 63, in keeplive
    self.send_auth_keeplive_msg()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/danmufm/client/douyu_danmu_manager.py", line 178, in send_auth_keeplive_msg
    self.danmu_auth_socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by curtank** [comment]
我感觉是作者在fetch_danmu里面写了死循环，好像没有跳出，你可以改一改。

**Comment by Galel** [comment]
貌似是最近弹幕结构又变了……
