### ISSUE TITLE
运行出错，是不是斗鱼改了页面的问题

### ISSUE THREAD

**Issue by abcdsxg** [twocucao/danmu.fm#13]
Traceback (most recent call last):
  File "/usr/local/bin/danmu.fm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/danmufm/danmu.py", line 117, in main
    parse_command()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/danmufm/danmu.py", line 107, in parse_command
    start_douyu_client()
  File "/usr/local/lib/python3.5/dist-packages/danmufm/danmu.py", line 112, in start_douyu_client
    DouyuClient(url).start()
  File "/usr/local/lib/python3.5/dist-packages/danmufm/client/douyu_client.py", line 51, in start
    auth_server_ip, auth_server_port = self.fetch_room_info(self.url)
  File "/usr/local/lib/python3.5/dist-packages/danmufm/client/douyu_client.py", line 75, in fetch_room_info
    room["gg_show"] = js["room_gg"]["show"]
KeyError: 'room_gg'

**Comment by hylarucoder** [comment]
虽然有些晚,但已经修复
