### ISSUE TITLE
No module named 'click'

### ISSUE THREAD

**Issue by MrCarlTang** [twocucao/danmu.fm#15]
Traceback (most recent call last):
  File "/home/carl/.local/bin/danmu.fm", line 7, in <module>
    from danmufm.danmu import main
  File "/home/carl/.local/lib/python3.5/site-packages/danmufm/danmu.py", line 73, in <module>
    import click
ImportError: No module named 'click'

**Comment by hylarucoder** [comment]
需要安装click 模块.
