### ISSUE TITLE
ubuntu 报错 no module named 'click'

### ISSUE THREAD

**Issue by rayeaster** [twocucao/danmu.fm#5]
Traceback (most recent call last):
  File "/usr/local/bin/danmu.fm", line 7, in <module>
    from danmufm.danmu import main
  File "/usr/local/lib/python3.4/dist-packages/danmufm/danmu.py", line 73, in <module>
    import click
ImportError: No module named 'click'

**Comment by hylarucoder** [comment]
hey,需要安装click模块呀
